### ISSUE TITLE
Create a subnet calculator

### ISSUE THREAD

**Issue by FreddyJilson** [FreddyJilson/netools#1]
**Description** 
A simple CLI subnet calculator tool. Provide support for class A, B and C type IP addresses.

**Requirements**
The CLI tool will ask the following input from user:
- IP address
- Subnet mask

Based on the above input, return the following calculated output:
- Network address
- Broadcast address
- Number of valid hosts per subnet
- Wildcard mask
- Number of mask bits in CIDR notation

**Example input**
- IP address: 192.168.92.3 
- Subnet mask: 255.255.255.0

**Example output**
- Network address: 192.168.92.0
- Broadcast address: 192.168.92.255
- Number of valid hosts per subnet: 254
- Wildcard mask: 255.255.255.0
- Number of mask bits in CIDR notation: 24

**Improvements or additions that would be nice to have:**
After providing the previous outputs, have an option for user to generate a random IP address in this subnet - ​192.168.92.10

**Comment by verlin** [comment]
Also, noticed that even though this issue is tagged "hacktoberfest" and shows up in hacktoberfest issue finders, the project isn't set to participate in Hacktoberfest. You'll need to add the topic to the repo for it to be a participating project:

https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/classifying-your-repository-with-topics
